# @package _global_

defaults:
  - override /data:  ids_data
  - override /model: gpt

project: 'FinetuneNoisyDNA'
experiment: 'TreconLM_pretrained_noisy' 

data: 
  artifact_name: File1-test-20250721_193623
  ground_truth_length: 60 
  block_size: 800
  batch_size: 20
  cleaned: True # to load preprocessed Noisy data (trailing C's removed)
  observation_size: 10
  lower_bound_obs_size: 2
  test_dataset_size: 50000
  test_seed: 34721


model: 
  checkpoint_path: <your.storage.path>/model_checkpoints/Reproduce/ids_data_nuc_CPRED_obs10_gt60_compute_final_60nt_reproduce/final_60nt_reproduce/train_run_gpt_20250804_222555/checkpoint_best.pt
  sampling:
    temperature: 1.0
    top_k: None
    strategy: greedy      # greedy or beam_search
    max_new_tokens: ${data.ground_truth_length}
    constrained_generation: False # to just generate ACTG 
