# @package _global_

defaults:
  - override /data:  ids_data
  - override /model: gpt

project: 'VariableLengthInference'
experiment: '60nt' #'TreconLM_pretrained_ids110_reproducibility' 

data: 
  artifact_name: test_dataset_seed34721_gl60_bs800_ds50000
  ground_truth_length: 60 
  block_size: 800
  batch_size: 100
  test_seed: 34721
  observation_size: 10
  lower_bound_obs_size: 2
  test_dataset_size: 50000


model: 
  checkpoint_path: "<your.storage.path>/model_checkpoints/VariableLength/ids_data_nuc_CPRED_obs10_gt[50, 120]_compute_var_length_50_120/var_length_50_120/train_run_gpt_20251006_122436/checkpoint_best.pt"
  sampling:
    temperature: 1.0
    top_k: None
    strategy: greedy      # greedy or beam_search, if beam_search, set beam_width below
    #beam_width: 6
    max_new_tokens: ${data.ground_truth_length}
    constrained_generation: False # to just generate ACTG 
