# @package _global_

defaults:
  - override /data:  ids_data
  - override /model: gpt

project: 'VariableLengthInference'
experiment: '180nt' 


data: 
  artifact_name: test_dataset_seed34721_gl180_bs2400_ds50000
  ground_truth_length: 180 
  block_size: 2400
  batch_size: 10
  test_seed: 34721
  observation_size: 10
  lower_bound_obs_size: 2
  test_dataset_size: 50000


model: 
  #checkpoint_path: <your.storage.path>/model_checkpoints/Reproduce/ids_data_nuc_CPRED_obs10_gt180_compute_final_180nt_reproduce/final_180nt_reproduce/train_run_gpt_20250806_151456/checkpoint_best.pt
  checkpoint_path: "<your.storage.path>/model_checkpoints/VariableLength/ids_data_nuc_CPRED_obs10_gt[60, 100]_compute_var_length_experiment/var_length_experiment/train_run_gpt_20250923_134830/checkpoint_best.pt"
  sampling:
    temperature: 1.0
    top_k: None
    strategy: greedy      # greedy or beam_search
    max_new_tokens: ${data.ground_truth_length}
    constrained_generation: True # to just generate ACTG 
