# @package _global_

defaults:
  - override /data:  ids_data
  - override /model: gpt

project: 'SubsOnly'
experiment: '1e18' #'TreconLM_pretrained_ids110_reproducibility' 

data: 
  artifact_name: CPRED_seed34721_gl110_bs1500_ds50000
  ground_truth_length: 110 
  block_size: 1500
  batch_size: 30 
  test_seed: 34721
  observation_size: 10
  lower_bound_obs_size: 2
  test_dataset_size: 50000


model: 
  checkpoint_path: <your.storage.path>/model_checkpoints/Substitutions/ids_data_nuc_CPRED_obs10_gt110_compute_subs_only_1e18/subs_only_1e18/train_run_gpt_20250923_111025/checkpoint_best.pt
  sampling:
    temperature: 1.0
    top_k: None
    strategy: greedy      # greedy or beam_search, if beam_search, set beam_width below
    #beam_width: 6
    max_new_tokens: ${data.ground_truth_length}
    constrained_generation: False # to just generate ACTG 
    analyze_vote_confidence: true
    vote_confidence_output_dir: <your.storage.path>/vote_confidence_results/1e18
    detailed_position_logging: true
