# @package _global_

defaults:
  - override /data:  ids_data
  - override /model: gpt

project: 'Inference'
experiment: 'TreconLM_noise_sweep' 

data: 
  artifact_name: None
  sweep: True
  ground_truth_length: 110 
  block_size: 1500
  batch_size: 400
  test_seed: 34721
  observation_size: 10
  lower_bound_obs_size: 2
  test_dataset_size: 5000

train: 
  early_stop_patience_iters: 150000  # default 15K iterations


model: 
  checkpoint_path: <your.storage.path>/models/TreconLM/pretrained/ids_110/checkpoint_best.pt
  sampling:
    temperature: 1.0
    top_k: None
    strategy: greedy      # greedy or beam_search
    max_new_tokens: ${data.ground_truth_length}
    constrained_generation: False # to just generate ACTG 
