# @package _global_

defaults:
  - override /data:  ids_data
  - override /model: gpt

project: 'FinetuneMicrosoft'
experiment: 'TreconLM_pretrained_microsoft' 

data: 
  artifact_name: Microsoft-test-20250721_160309
  ground_truth_length: 110 
  block_size: 1500
  batch_size: 50
  test_seed: 34721
  observation_size: 10
  lower_bound_obs_size: 2
  test_dataset_size: 5000



model: 
  checkpoint_path: <your.storage.path>/model_checkpoints/Reproduce/ids_data_nuc_CPRED_obs10_gt110_compute_final_110nt_reproduce/final_110nt_reproduce/train_run_gpt_20250806_100623/checkpoint_best.pt
  sampling:
    temperature: 1.0
    top_k: None
    strategy: greedy      # greedy or beam_search
    max_new_tokens: ${data.ground_truth_length}
    constrained_generation: False # to just generate ACTG 
