# @package _global_
defaults:
  - override /general: scratch 
  - override /data: ids_data
  - override /model: gpt
  - override /train: base

project: TRACE_RECONSTRUCTION
experiment: gpt_O_3e19_final

general:
  checkpoint_path:  
  #train_time: '' 

data:
  sequence_type: nuc
  target_type: CPRED 
  observation_size: 10
  ground_truth_length: 110
  lower_bound_obs_size: 2
  block_size: 1500
  test: true
  test_seed: 34721
  test_dataset_size: 50000

train:
  ddp: true
  eval_interval: 500
  log_interval: 10
  eval_iters: 1000
  eval_only: false
  always_interval: 500
  always_save_checkpoint: true
  device: cuda:0
  gradient_accumulation_steps: 8 
  batch_size: 63
  learning_rate: 0.0005590169943749475
  max_iters: 313027 #from scaling laws to achieve fixed compute 
  weight_decay: 0.1
  beta1: 0.9
  beta2: 0.95
  grad_clip: 1.0
  decay_lr: true
  warmup_iters: 0 #placeholder set to 5% of max_iters in train()
  min_lr: 0.0
  lr_decay_iters: ${train.max_iters} 

model:
  gpt_params: 
    n_layer: 12
    n_head: 6
    n_embd: 384
    dropout: 0
    bias: false

wandb: 
  wandb_log: true