# @package _global_

defaults:
  - override /general: resume  
  - override /data: ids_data
  - override /model: gpt
  - override /train: base

project: VariableLength
experiment: var_length_50_120

general:
  checkpoint_path: <your.storage.path>
  train_time: '20251006_122436'

data:
  sequence_type: nuc
  target_type: CPRED 
  observation_size: 10
  ground_truth_length: [50,120]
  lower_bound_obs_size: 2
  block_size: 2400
  test: true
  test_seed: 34721
  test_dataset_size: 50000

train:
  ddp: true
  eval_interval: 500
  log_interval: 10
  eval_iters: 1000
  eval_only: false
  always_interval: 500
  always_save_checkpoint: true
  device: cuda:0
  gradient_accumulation_steps: 8 
  batch_size: 50
  learning_rate: 1e-4
  max_iters: 459912 # # 1e20 compute
  weight_decay: 0.1 
  beta1: 0.9
  beta2: 0.95
  grad_clip: 1.0
  decay_lr: true
  warmup_iters: 0 #placeholder set to 5% of max_iters in train()
  min_lr: 0.0
  lr_decay_iters: ${train.max_iters}
  train_seed: 100

model:
  gpt_params: 
    n_layer: 12
    n_head: 8
    n_embd: 512
    dropout: 0.1
    bias: false

wandb: 
  wandb_log: true
  test_project: TRACE_RECONSTRUCTION