# @package _global_

defaults:
  - override /data:  ids_data
  - override /model: gpt

project: 'Inference'
experiment: 'TreconLM_fixedN50' 

data: 
  artifact_name: None
  sweep: True
  ground_truth_length: 110 
  block_size: 6500
  batch_size: 5
  test_seed: 34721
  observation_size: 50
  lower_bound_obs_size: 50
  test_dataset_size: 5000


model: 
  checkpoint_path: <your.storage.path>/model_checkpoints/TRACE_RECONSTRUCTION/ids_data_nuc_CPRED_obs50_gt110_compute_fixed_N50_b256/fixed_N50_b256/train_run_gpt_20250626_161239/checkpoint_best.pt
  sampling:
    temperature: 1.0
    top_k: None
    strategy: greedy      # greedy or beam_search
    max_new_tokens: ${data.ground_truth_length}
    constrained_generation: False # to just generate ACTG 
