# @package _global_

defaults:
  - override /data:  ids_data
  - override /model: gpt

project: 'Inference'
experiment: 'fixed_N40_b256_more_iter_c5800' 

data: 
  artifact_name: None
  sweep: True
  ground_truth_length: 110 
  block_size: 5750
  batch_size: 10
  test_seed: 34721
  observation_size: 40
  lower_bound_obs_size: 40
  test_dataset_size: 5000


model: 
  checkpoint_path: <your.storage.path>/model_checkpoints/TRACE_RECONSTRUCTION/ids_data_nuc_CPRED_obs40_gt110_compute_fixed_N40_b256_more_iter_c5800/fixed_N40_b256_more_iter_c5800/train_run_gpt_20250715_223718/checkpoint_best.pt
  sampling:
    temperature: 1.0
    top_k: None
    strategy: greedy      # greedy or beam_search
    max_new_tokens: ${data.ground_truth_length}
    constrained_generation: False # to just generate ACTG 
